### ISSUE TITLE
Support Lexicon rewrite

### ISSUE THREAD

**Issue by snarfed** [snarfed/lexrpc#2]
Too early to do anything here, but evidently Lexicon is planning a major revision, eg moving away from JSON Schema! https://github.com/bluesky-social/atproto/issues/372

**Comment by ShreyanJain9** [comment]
They rewrote Lexicon back in April 🙂 I'm guessing lexrpc supports the new one already but haven't tested :D 
But, maybe this issue should be closed lol

**Comment by snarfed** [comment]
Hah, yes, thanks!
